services:

  waha:
    image: devlikeapro/waha:latest
    container_name: wpp_bot_waha
    restart: always

    ports:
      - "3000:3000"
    
    volumes:
      # salva as sessões
      - './.sessions:/app/.sessions'

      # salva as mídias
      - './.media:/app/.media'

    env_file:
      - .env

  api:
      build:
        context: .
        dockerfile: Dockerfile.api
      container_name: wpp_bot_api
      ports:
        - '5000:5000'
      env_file:
        - .env
