services:

  waha:
    image: devlikeapro/waha:latest
    container_name: wpp_bot_waha
    restart: always

    ports:
      - "3000:3000"
    
    volumes:
      # salva as sessões
      - './.sessions:/app/.sessions'

      # salva as mídias
      - './.media:/app/.media'

    env_file:
      - .env
    
  api:
    build:
      context: .
      dockerfile: dockerfile.api
    container_name: wpp_bot_api
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      #- ./bot:/app/bot
    env_file:
      - .env
